/**
 * Multiple fishing lakes scattered across 1 map (replacing the previous single fixed ellipse lake) — see
 * docs/concept_brief.md section 1 + docs/progress.md log of the day this design changed.
 *
 * Lake shape is now a REAL GAME RULE (gating the casting of the rod — see backend/src/systems/fishing.ts),
 * no longer purely cosmetic, so it must reside in shared/ rather than just frontend/render.ts as
 * before. The distorted polygon of each lake is GENERATED by a deterministic function (seeded hash based on lake.id, see
 * hash.ts) instead of hardcoding coordinates manually — thus frontend and backend (2 separate processes) always
 * calculate the exact same shape without transmitting the polygon over the network.
 *
 * Any changes to this file must be logged in docs/progress.md (see AGENTS.md).
 */

import { FISH_CATALOG, getFishSpecies, type FishSpecies, WORLD_WIDTH } from "./constants.js";
import { hash01, hashString } from "./hash.js";

export interface LakePoint {
  x: number;
  y: number;
}

/** Standing within this range from the lake boundary (even if standing inside the lake, distance = 0) allows casting
 * the rod into that lake — see findNearestLake + backend/src/systems/fishing.ts#tryCast. */
export const LAKE_CAST_RANGE = 140;

interface LakeShapeInput {
  id: string;
  name: string;
  centerX: number;
  centerY: number;
  baseRadiusX: number;
  baseRadiusY: number;
  vertexCount: number;
  /** 0..1 — the distortion of the lake shore compared to a regular ellipse (0 = perfect ellipse, higher means more "distorted"). */
  jitter: number;
  /** speciesId (see FISH_CATALOG) -> random weight when a fish bites IN THIS LAKE. Not every lake
   * has all 8 species — each lake only has a subset, providing a reason to fish in different lakes to collect them all. */
  fishWeights: Record<string, number>;
}

/** Axis-aligned bounding box of the lake in WORLD COORDINATES (with centerX/centerY added to polygon) —
 * calculated once at module load. Used as a cheap filter (O(1)) before running the expensive point-in-polygon
 * O(n vertices): a point outside the AABB is definitely outside the lake, and the distance to the AABB is
 * a lower bound of the actual distance to the lake shore — see aabbDistanceToLake + hot functions below. */
export interface LakeBounds {
  minX: number;
  minY: number;
  maxX: number;
  maxY: number;
}

export interface LakeDefinition extends LakeShapeInput {
  /** RELATIVE coordinates to (centerX, centerY), generated once at module load — see generateBlobPolygon. */
  polygon: LakePoint[];
  /** AABB world-space, precomputed from polygon — see LakeBounds. */
  bounds: LakeBounds;
}

/** AABB world-space of a lake from polygon (relative coordinates) + lake center. */
function computeLakeBounds(centerX: number, centerY: number, polygon: LakePoint[]): LakeBounds {
  let minX = Infinity;
  let minY = Infinity;
  let maxX = -Infinity;
  let maxY = -Infinity;
  for (const p of polygon) {
    const wx = centerX + p.x;
    const wy = centerY + p.y;
    if (wx < minX) minX = wx;
    if (wx > maxX) maxX = wx;
    if (wy < minY) minY = wy;
    if (wy > maxY) maxY = wy;
  }
  return { minX, minY, maxX, maxY };
}

/** Distance from a world point to the AABB of the lake (0 if inside the AABB) — ALWAYS <= actual distance
 * to the lake shore, so it can be used as a lower bound to quickly skip far lakes without point-in-polygon
 * or scanning every edge. */
export function aabbDistanceToLake(lake: LakeDefinition, worldX: number, worldY: number): number {
  const b = lake.bounds;
  const dx = worldX < b.minX ? b.minX - worldX : worldX > b.maxX ? worldX - b.maxX : 0;
  const dy = worldY < b.minY ? b.minY - worldY : worldY > b.maxY ? worldY - b.maxY : 0;
  return Math.hypot(dx, dy);
}

/** Generates a closed distorted polygon from a base ellipse — the radius of each vertex is jittered by a seeded
 * hash (seed = hash of lake.id + vertex index), making it 100% deterministic (no Math.random used) while remaining
 * different between lakes and between vertices within the same lake. */
function generateBlobPolygon(shape: LakeShapeInput): LakePoint[] {
  const baseSeed = hashString(shape.id);
  const points: LakePoint[] = [];
  for (let i = 0; i < shape.vertexCount; i++) {
    const angle = (i / shape.vertexCount) * Math.PI * 2;
    const jitterRoll = hash01(baseSeed + i * 97.13);
    const radiusScale = 1 + (jitterRoll - 0.5) * 2 * shape.jitter;
    points.push({
      x: Math.cos(angle) * shape.baseRadiusX * radiusScale,
      y: Math.sin(angle) * shape.baseRadiusY * radiusScale,
    });
  }
  return points;
}

// ---- 6 lakes, scattered across the world (see WORLD_WIDTH/HEIGHT in constants.ts) — different sizes/distortions/fish types
// as requested: small/round lakes near the starting point only have common fish, large/distorted/far lakes lean towards
// rare-legendary fish. Ensure all 8 species in FISH_CATALOG appear in at least one lake.
const LAKE_SHAPES: LakeShapeInput[] = [
  {
    id: "ao_lang",
    name: "Village Pond",
    centerX: 0,
    centerY: 0,
    baseRadiusX: 320,
    baseRadiusY: 280,
    vertexCount: 10,
    jitter: 0.15,
    fishWeights: { silver_carp: 30, minnow: 26, fish_leviathan: 999999 },
  },
  {
    id: "ho_guong",
    name: "Mirror Lake",
    centerX: 2000,
    centerY: -1300,
    baseRadiusX: 520,
    baseRadiusY: 440,
    vertexCount: 12,
    jitter: 0.2,
    fishWeights: { silver_carp: 20, catfish: 20, tilapia: 12, fish_leviathan: 999999 },
  },
  {
    id: "ho_ran",
    name: "Serpent Lake",
    centerX: -2500,
    centerY: -300,
    baseRadiusX: 900,
    baseRadiusY: 300,
    vertexCount: 16,
    jitter: 0.35,
    fishWeights: { tilapia: 12, snakehead: 9, catfish: 15, fish_leviathan: 999999 },
  },
  {
    id: "dam_sen",
    name: "Lotus Marsh",
    centerX: -1100,
    centerY: 2200,
    baseRadiusX: 400,
    baseRadiusY: 360,
    vertexCount: 11,
    jitter: 0.4,
    fishWeights: { snakehead: 10, koi: 4, fish_leviathan: 999999 },
  },
  {
    id: "vinh_bang",
    name: "Ice Bay",
    centerX: 2700,
    centerY: 1900,
    baseRadiusX: 750,
    baseRadiusY: 620,
    vertexCount: 14,
    jitter: 0.4,
    fishWeights: { tilapia: 6, koi: 5, giant_barb: 4, fish_leviathan: 999999 },
  },
  {
    id: "ho_rong",
    name: "Dragon Lake",
    centerX: -2500,
    centerY: -2000,
    baseRadiusX: 850,
    baseRadiusY: 650,
    vertexCount: 13,
    jitter: 0.25,
    fishWeights: { koi: 3, giant_barb: 4, golden_dragonfish: 1, fish_leviathan: 999999 },
  },
  // ---- 1 Single River (Single winding river connecting left to right/sea) ----
  {
    id: "song_chinh",
    name: "Han River",
    centerX: 0,
    centerY: 0,
    baseRadiusX: 3700,
    baseRadiusY: 80,
    vertexCount: 80,
    jitter: 0,
    fishWeights: { silver_carp: 20, tilapia: 20, catfish: 15, snakehead: 10, fish_leviathan: 999999 },
  },
  // ---- Sea on the right (Sea on the right) ----
  {
    id: "bien_dong",
    name: "East Sea",
    centerX: 4100,
    centerY: 0,
    baseRadiusX: 400,
    baseRadiusY: 3800,
    vertexCount: 18,
    jitter: 0.08,
    fishWeights: { butterfish: 22, mackerel: 14, tuna: 6, baby_shark: 1, fish_leviathan: 999999 },
  },
];

function generateRiverPolygon(): LakePoint[] {
  const points: LakePoint[] = [];
  const startX = -3400;
  const endX = 3900;
  const steps = 65;
  const width = 150;

  const riverY = (x: number) => {
    return 450 * Math.sin(x / 1100) - 800;
  };

  // Top bank
  for (let i = 0; i <= steps; i++) {
    const x = startX + (i / steps) * (endX - startX);
    const jitterVal = (hash01(987 + i * 17.3) - 0.5) * 20;
    points.push({
      x,
      y: riverY(x) - (width / 2 + jitterVal),
    });
  }

  // Bottom bank
  for (let i = steps; i >= 0; i--) {
    const x = startX + (i / steps) * (endX - startX);
    const jitterVal = (hash01(123 + i * 17.3) - 0.5) * 20;
    points.push({
      x,
      y: riverY(x) + (width / 2 + jitterVal),
    });
  }

  return points;
}

export const LAKE_DEFINITIONS: LakeDefinition[] = LAKE_SHAPES.map((shape) => {
  const polygon = shape.id === "song_chinh" ? generateRiverPolygon() : generateBlobPolygon(shape);
  return {
    ...shape,
    polygon,
    bounds: computeLakeBounds(shape.centerX, shape.centerY, polygon),
  };
});

const LAKE_BY_ID = new Map(LAKE_DEFINITIONS.map((l) => [l.id, l]));

export function getLakeById(id: string | null | undefined): LakeDefinition | undefined {
  return id != null ? LAKE_BY_ID.get(id) : undefined;
}

// ---- Polygon geometry (shared for rod casting gate in backend + drawing/skip-decor in frontend) ----

export function isPointInPolygon(localX: number, localY: number, polygon: LakePoint[]): boolean {
  let inside = false;
  for (let i = 0, j = polygon.length - 1; i < polygon.length; j = i++) {
    const xi = polygon[i].x;
    const yi = polygon[i].y;
    const xj = polygon[j].x;
    const yj = polygon[j].y;
    const intersect = yi > localY !== yj > localY && localX < ((xj - xi) * (localY - yi)) / (yj - yi) + xi;
    if (intersect) inside = !inside;
  }
  return inside;
}

function distanceToSegment(px: number, py: number, ax: number, ay: number, bx: number, by: number): number {
  const dx = bx - ax;
  const dy = by - ay;
  const lenSq = dx * dx + dy * dy;
  let t = lenSq === 0 ? 0 : ((px - ax) * dx + (py - ay) * dy) / lenSq;
  t = Math.max(0, Math.min(1, t));
  return Math.hypot(px - (ax + t * dx), py - (ay + t * dy));
}

/** Raw distance to the nearest edge — DOES NOT collapse to 0 when inside the polygon (different from
 * distanceToPolygon below). Used for "standing near the lake edge" (shore decoration, see
 * frontend/src/render.ts) — where we need to distinguish "near edge" from "deep inside the lake", unlike the casting gate
 * (which only needs to know if it is within range, see distanceToPolygon). */
export function distanceToPolygonBoundary(localX: number, localY: number, polygon: LakePoint[]): number {
  let minDist = Infinity;
  for (let i = 0, j = polygon.length - 1; i < polygon.length; j = i++) {
    const d = distanceToSegment(localX, localY, polygon[j].x, polygon[j].y, polygon[i].x, polygon[i].y);
    if (d < minDist) minDist = d;
  }
  return minDist;
}

/** 0 if (localX, localY) is inside the polygon, otherwise the distance to the nearest edge. */
export function distanceToPolygon(localX: number, localY: number, polygon: LakePoint[]): number {
  if (isPointInPolygon(localX, localY, polygon)) return 0;
  return distanceToPolygonBoundary(localX, localY, polygon);
}

export function isInsideLake(lake: LakeDefinition, worldX: number, worldY: number): boolean {
  // Cheap AABB reject first — a point outside the bounding box can't be inside the polygon, so we
  // skip the O(n) point-in-polygon scan for the (common) case of a point far from this lake.
  const b = lake.bounds;
  if (worldX < b.minX || worldX > b.maxX || worldY < b.minY || worldY > b.maxY) return false;
  return isPointInPolygon(worldX - lake.centerX, worldY - lake.centerY, lake.polygon);
}

/** Whether currently inside ANY lake — used to block walking on water (see
 * backend/src/systems/movement.ts) and to skip drawing/painting meadows on water (see
 * frontend/src/render.ts). */
export function isInsideAnyLake(worldX: number, worldY: number): boolean {
  return LAKE_DEFINITIONS.some((lake) => isInsideLake(lake, worldX, worldY));
}

export function distanceToLakeEdge(lake: LakeDefinition, worldX: number, worldY: number): number {
  return distanceToPolygon(worldX - lake.centerX, worldY - lake.centerY, lake.polygon);
}

/** Same as distanceToLakeEdge but does not collapse to 0 when inside the lake — see distanceToPolygonBoundary. */
export function distanceToLakeBoundary(lake: LakeDefinition, worldX: number, worldY: number): number {
  return distanceToPolygonBoundary(worldX - lake.centerX, worldY - lake.centerY, lake.polygon);
}

/** The nearest lake from any point + the distance to that lake's boundary (0 if standing inside the lake) —
 * used to gate rod casting (LAKE_CAST_RANGE) and determine which lake is being fished. */
export function findNearestLake(worldX: number, worldY: number): { lake: LakeDefinition; distance: number } | null {
  let best: { lake: LakeDefinition; distance: number } | null = null;
  for (const lake of LAKE_DEFINITIONS) {
    // aabbDistanceToLake là cận dưới của khoảng cách thật tới biên hồ — nếu ngay cả cận dưới này đã
    // >= khoảng cách tốt nhất tìm được, không cần chạy distanceToLakeEdge (O(n cạnh)) cho hồ này.
    if (best && aabbDistanceToLake(lake, worldX, worldY) >= best.distance) continue;
    const d = distanceToLakeEdge(lake, worldX, worldY);
    if (!best || d < best.distance) best = { lake, distance: d };
  }
  return best;
}

/** Weighted random pick from the lake-specific fish pool (different from pickRandomFishSpecies in constants.ts,
 * which randomly selects across the entire FISH_CATALOG regardless of the lake). */
export function pickRandomFishSpeciesForLake(lake: LakeDefinition): FishSpecies {
  const entries = Object.entries(lake.fishWeights);
  const totalWeight = entries.reduce((sum, [, w]) => sum + w, 0);
  let r = Math.random() * totalWeight;
  for (const [speciesId, weight] of entries) {
    if (r < weight) return getFishSpecies(speciesId) ?? FISH_CATALOG[0];
    r -= weight;
  }
  return getFishSpecies(entries[0]?.[0]) ?? FISH_CATALOG[0];
}

export function isInsideMountains(worldX: number, worldY: number): boolean {
  // Bounding box of the left mountains around y = -1200
  return worldX < -WORLD_WIDTH / 2 + 350 && worldY > -1700 && worldY < -700;
}
